CREATE SCHEMA PPAP;

USE PPAP;

CREATE TABLE STORE_OWNER(
	OWNER_NUM INT NOT NULL AUTO_INCREMENT,
    OWNER_NAME VARCHAR(20) NOT NULL,
    ID VARCHAR(20) NOT NULL,
    PW VARCHAR(20) NOT NULL,
    PHONE VARCHAR(13),
    EMAIL VARCHAR(50),
    PRIMARY KEY (OWNER_NUM)
) AUTO_INCREMENT = 1001, CHARSET = UTF8MB4;

CREATE TABLE STORE(
	STORE_NUM INT NOT NULL AUTO_INCREMENT,
    STORE_NAME VARCHAR(50) NOT NULL,
    LOCATION VARCHAR(100) NOT NULL,
    TEL VARCHAR(12),
    OWNER_NUM INT NOT NULL,
    PRIMARY KEY (STORE_NUM),
    FOREIGN KEY (OWNER_NUM) REFERENCES STORE_OWNER(OWNER_NUM) 
    ON DELETE CASCADE
) AUTO_INCREMENT = 100001, CHARSET = UTF8MB4;

CREATE TABLE CUSTOMER(
	CUSTOMER_NUM INT NOT NULL AUTO_INCREMENT,
    CUSTOMER_NAME VARCHAR(20) NOT NULL,
    ID VARCHAR(20) NOT NULL,
    PW VARCHAR(20) NOT NULL,
    PHONE VARCHAR(13),
    EMAIL VARCHAR(50),
    PRIMARY KEY (CUSTOMER_NUM)
) AUTO_INCREMENT = 10001, CHARSET = UTF8MB4;
    
CREATE TABLE FRUITS(
	FRUITS_NUM INT NOT NULL AUTO_INCREMENT,
    FRUITS_NAME VARCHAR(10) NOT NULL,
    PRICE INT NOT NULL,
    IMAGE VARCHAR(255) NOT NULL,
    FRUITS_DESC VARCHAR(255) NOT NULL,
    PRIMARY KEY(FRUITS_NUM)
) CHARSET = UTF8MB4;

CREATE TABLE PRODUCER(
	PRODUCER_NUM INT NOT NULL AUTO_INCREMENT,
    FARM VARCHAR(30) NOT NULL,
    ADDRESS VARCHAR(50) NOT NULL,
    PHONE VARCHAR(13) NOT NULL,
    FRUITS_NUM INT NOT NULL,
    PRIMARY KEY (PRODUCER_NUM),
    FOREIGN KEY (FRUITS_NUM) REFERENCES FRUITS(FRUITS_NUM)
    ON DELETE CASCADE
) CHARSET = UTF8MB4;

CREATE TABLE SUPPLY(
	SUPPLY_NUM INT NOT NULL AUTO_INCREMENT,
    STORE_NUM INT NOT NULL,
    COUNT INT NOT NULL,
    SUPPLY_PRICE INT NOT NULL,
    SUPPLY_DATE DATETIME NOT NULL,
    PRODUCER_NUM INT,
    PRIMARY KEY (SUPPLY_NUM, STORE_NUM),
    FOREIGN KEY (STORE_NUM) REFERENCES STORE(STORE_NUM)
    ON DELETE CASCADE,
    FOREIGN KEY (PRODUCER_NUM) REFERENCES PRODUCER(PRODUCER_NUM)
) CHARSET = UTF8MB4;

CREATE TABLE EXPEND(
	EXPEND_NUM INT NOT NULL AUTO_INCREMENT,
    STORE_NUM INT NOT NULL,
    EXPEND_PRICE INT NOT NULL,
    EXPEND_DATE DATETIME NOT NULL,
    SUPPLY_NUM INT NOT NULL,
    PRIMARY KEY (EXPEND_NUM, STORE_NUM),
    FOREIGN KEY (STORE_NUM) REFERENCES STORE(STORE_NUM)
    ON DELETE CASCADE,
    FOREIGN KEY (SUPPLY_NUM) REFERENCES SUPPLY(SUPPLY_NUM)
) CHARSET = UTF8MB4;
    
CREATE TABLE PRODUCT(
	PRODUCT_NUM INT NOT NULL AUTO_INCREMENT,
    STORE_NUM INT NOT NULL,
    PRODUCT_NAME VARCHAR(20) NOT NULL,
    QUANTITY INT NOT NULL DEFAULT 0,
    EXPIRE_DATE DATETIME NOT NULL,
    PRICE INT NOT NULL,
	PRODUCT_STATUS VARCHAR(10) NOT NULL DEFAULT "판매중",
    SUPPLY_NUM INT NOT NULL,
    PRIMARY KEY (PRODUCT_NUM, STORE_NUM),
    FOREIGN KEY (STORE_NUM) REFERENCES STORE(STORE_NUM)
    ON DELETE CASCADE,
    FOREIGN KEY (SUPPLY_NUM) REFERENCES SUPPLY(SUPPLY_NUM)
) CHARSET = UTF8MB4;

CREATE TABLE SALES(
	SALES_NUM INT NOT NULL AUTO_INCREMENT,
    PRODUCT_NUM INT NOT NULL,
    STORE_NUM INT NOT NULL,
    SALES_DATE DATETIME NOT NULL,
    SALES_PRICE INT NOT NULL,
    SALES_QUANTITY INT NOT NULL,
    ETC BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (SALES_NUM),
    FOREIGN KEY (PRODUCT_NUM) REFERENCES PRODUCT(PRODUCT_NUM)
    ON DELETE CASCADE,
    FOREIGN KEY (STORE_NUM) REFERENCES STORE(STORE_NUM)
    ON DELETE CASCADE
) CHARSET = UTF8MB4;
    
CREATE TABLE ORDERED(
	ORDERED_NUM INT NOT NULL AUTO_INCREMENT,
    STORE_NUM INT NOT NULL,
    PRODUCT_NUM INT NOT NULL,
    CUSTOMER_NUM INT NOT NULL,
    ORDERED_QUANTITY INT NOT NULL,
    ORDERED_DATE DATETIME NOT NULL,
    PRIMARY KEY (ORDERED_NUM),
    FOREIGN KEY (STORE_NUM) REFERENCES STORE(STORE_NUM)
    ON DELETE CASCADE,
    FOREIGN KEY (PRODUCT_NUM) REFERENCES PRODUCT(PRODUCT_NUM)
    ON DELETE CASCADE,
    FOREIGN KEY (CUSTOMER_NUM) REFERENCES CUSTOMER(CUSTOMER_NUM)
    ON DELETE CASCADE
) CHARSET = UTF8MB4;